### ISSUE TITLE
Not avaliable in the in-game 'online content' browser.

### ISSUE THREAD

**Issue by GoodClover** [sodomon2/minetest-paper-cut-out#2]
This texture pack is in the ContentDB but for some reason it doesn't appear on the in-game online content browser.
Not sure how texture packs work fully so it may be something I'm doing wrong.

**Comment by sodomon2** [comment]
> This texture pack is in the ContentDB but for some reason it doesn't appear on the in-game online content browser.
> Not sure how texture packs work fully so it may be something I'm doing wrong.

@GoodClover maybe you are doing something wrong, because as you can see in the following screenshot if it appears available in the contendb search engine

![image](https://user-images.githubusercontent.com/49420637/187718693-80ffcdb0-20be-42c6-b4a2-205d01821d91.png)
